RANDOM_STATE = 42
N_CLIENTS = 8000
TRAIN_END_DATE = "2023-12-31"
TEST_START_DATE = "2024-01-01"
MONTHS_FORWARD = 24

PD_DEFAULT_THRESHOLD = 0.50
STAGE2_PD_RELATIVE_MULTIPLIER = 2.0
STAGE2_PD_MULTIPLIER = STAGE2_PD_RELATIVE_MULTIPLIER
STAGE2_PD_ABSOLUTE_INCREASE = 0.05
STAGE2_DPD_THRESHOLD = 30
STAGE3_DPD_THRESHOLD = 90
DISCOUNT_RATE_ANNUAL = 0.1475
SECTOR_TIME_SERIES_MONTHS = 36

USE_REAL_MACRO = True
MACRO_WIDE_PATH = "data/processed/macro_factors_wide.csv"
MACRO_REFERENCE_DATE = None
MACRO_MAX_FFILL_MONTHS = 3
